### ISSUE TITLE
Dependencies mechanism is broken in the lastest library version

### ISSUE THREAD

**Issue by kllara** [unicesi/amelia#12]
I upgraded the library to the latest release. When I am using that version, some commands are not executed according to the specified dependencies.

Best regards,

Kllara

**Comment by jachinte** [comment]
Context: this occur when several dependencies are executed in different hosts. @juan3036 have you experienced something like this? (I'm assuming you're using the latest version too).

**Comment by juan3036** [comment]
Hi @jachinte 
Yes, I'm using the lastest version of the library. Until now, I had not experienced any behavior like the described in my 'deployments' deployed by Amelia.

**Comment by jachinte** [comment]
@juan3036 ok, thanks! then we have to wait until @kllara tests the [recent changes](https://github.com/unicesi/amelia/commit/828bbf69084760776533830832e8da3453cb0c03) to continue with this issue. Although I do not see a problem with the library.

**Comment by jachinte** [comment]
@kllara do you have any news on this?

**Comment by kllara** [comment]
It's working now! thanks :+1:

**Comment by juan3036** [comment]
@jachinte Did you make new changes to avoid this?

**Comment by jachinte** [comment]
@kllara I'm glad it is working well.
@juan3036 I did make a change in this [commit](https://github.com/unicesi/amelia/commit/828bbf69084760776533830832e8da3453cb0c03) but it seems  the problem was related to the implementation, not the library. Although my recommendation is to update to the latest version.
