### ISSUE TITLE
Missing classes at runtime

### ISSUE THREAD

**Issue by kllara** [unicesi/amelia#16]
Classes `org.eclipse.xtext.xbase.lib.Functions.Function0` and `org.eclipse.xtext.xbase.lib.Procedures.Procedure0` are not present in the assembly jar. These classes are used in [`org.amelia.dsl.lib.util.RetryableDeployment`](https://github.com/unicesi/amelia/blob/master/maven/org.amelia.dsl.lib/src/main/java/org/amelia/dsl/lib/util/RetryableDeployment.java).

**Comment by jachinte** [comment]
The reason why this is happening is that the maven dependency is in scope "provided". As these interfaces are really simple, it is not worth adding them to the assembly jar, so I am creating them as internal (static) interfaces.
