### ISSUE TITLE
Problem with deployment of multiple instances of a single subsystem

### ISSUE THREAD

**Issue by lfrivera** [unicesi/amelia#36]
Hi,

I am having a problem when my deployment specification requires many instances of a single subsystem. Apparently, the dependencies between subsystems are not being fulfilled at runtime. The following example describes the situation mentioned previously:

I have a subsystem called "Monitors", which implementation is shown below:

`depends on Run_Bridge_Intermediate_Server

subsystem Monitors
{
    param Host host
    param String name  

```
on host
{
    directory:
        cd "/home/carvajal/Documents/carvajal/"

    execute:directory;

        run "memory-monitor" -libpath #[
                "jars/monitoring.jar",
                "lib/org.pascani.dsl.lib-0.0.1-SNAPSHOT-dependencies.jar",
                "lib/new-personalized-events-with-carvajal.jar",
                "lib/slf4j-api-1.7.10.jar",
                "lib/sigar.jar"
            ] -s "startMemoryMonitor" -m "startMemoryMonitoring" -p name
}
```

}`

I also have a subsystem called "JMeter_Restore" that depends on the execution of all monitors, and in my deployment specification, I instantiate each "monitor" as following:

`for(i: 1..1)
    {
        deployHelper.deploy([

```
        add(new Monitors(consumHost1,"consum1"))
        add(new Monitors(consumHost2,"consum2"))
        add(new Monitors(consumHost3,"consum3"))
        add(new Monitors(consumHost4,"consum4"))

        add(new JMeter_Restore(hostJmeter, "XML-REST-1MB.jmx",hostBD))
        start(true) 

    ],3)
}`
```

Nevertheless, only the first monitor is being deployed and the subsystem "JMeter_Restore" is deployed even when not all monitors were deployed.

I really appreciate your help on this issue,

Warm regards,

Felipe Rivera

**Comment by jachinte** [comment]
This is probably happening because both the `hashcode` and `equals` methods rely on the `alias` attribute, and all instances of the same subsystem share the alias. I will fix this as soon as I can.

**Comment by jachinte** [comment]
Hi @lfrivera,
Could you please try again?

**Comment by lfrivera** [comment]
Hi @jachinte,

First of all, I want to thank you for your help. 

I've just updated Amelia from the update site and some things start to being apparently wrong. The dependencies between subsystems are not working and two kind of messages are appearing: "Subsystems cannot depend on deployment strategies" and "Subsystem cannot be resolved to a type"

I would appreciate your help again!

I have attached two images with the problems that are occurring.

![error](https://cloud.githubusercontent.com/assets/20957015/18329804/04f9e9d6-751b-11e6-8a74-0aa845455203.png)
![error2](https://cloud.githubusercontent.com/assets/20957015/18329806/04fb8a3e-751b-11e6-9375-67c9e36d850a.png)

**Comment by jachinte** [comment]
I can recognize the first error. It's because while trying to retain the user from adding dependencies between subsystems and deployments (which does not make any sense) I ended up adding a bug. I will check on that.

The second error is happening probably because of the first error; as there is a problem, subsystems are not compiled.

**Comment by jachinte** [comment]
I can recognize the first error. It's because while trying to retain the user from adding dependencies between subsystems and deployments (which does not make any sense) I ended up adding a bug. I will check on that.

The second error is happening probably because of the first error; as there is a problem, subsystems are not compiled.

**Comment by jachinte** [comment]
@lfrivera all you have to do is replace line 490 of [AmeliaValidator.xtend](https://github.com/unicesi/amelia/blob/master/plugins/org.amelia.dsl/src/org/amelia/dsl/validation/AmeliaValidator.xtend#L490) with the following:

```
DependDeclaration case extensionDecl.element instanceof DeploymentDeclaration: {
```

Then:
1. Test it and update the artifacts in the (github) update site.
2. If it works, create an issue "v0.7.10-SNAPSHOT" and tag it as "release". The content is: "@rultor release, tag is `0.7.10-SNAPSHOT`". When rultor finishes, close the issue.

Thanks!
