### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [unicesi/amelia#57]
Hello Amelia team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Amelia project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by jachinte** [comment]
Hi @miklossy 
Thanks for reaching out.

Here is the information:

```html
<tr>
	<td><a href="https://github.com/unicesi/amelia">Amelia DSL</a></td>
	<td>Amelia is a compact DSL tailored for specifying and executing deployment workflows for distributed software systems.</td>
	<td>LGPL-3.0</td>
	<td>Software Deployment</td>
	<td>Miguel Jiménez, Gabriel Tamura</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @jachinte !

**Comment by miklossy** [comment]
The `Amelia DSL` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
